openapi: 3.1.0
info:
  title: Cognite 3D Asset Mapping Entity matching API
  description: "# Introduction\nThis is the reference documentation for the Cognite API with\nan overview of all the available methods.\n\n# Postman\nSelect the **Download** button to download our OpenAPI specification to get started.\n\nTo import your data into Postman, select **Import**, and the Import modal opens.\nYou can import items by dragging or dropping files or folders. You can choose how to import your API and manage the import settings in **View Import Settings**.\n\nIn the Import Settings, set the **Folder organization** to **Tags**, select\n**Enable optional parameters** to turn off the settings, and select **Always inherit authentication** to turn on the settings. Select **Import**.\n\nSet the Authorization to **Oauth2.0**. By default, the settings are for Open Industrial Data. Navigate to [Cognite Hub](https://hub.cognite.com/open-industrial-data-211) to understand how to get the credentials for use in Postman.\n\nFor more information, see [Getting Started with Postman](https://developer.cognite.com/dev/guides/postman/).\n\n# Pagination\nMost resource types can be paginated, indicated by the field `nextCursor` in the response.\nBy passing the value of `nextCursor` as the cursor you will get the next page of `limit` results.\nNote that all parameters except `cursor` has to stay the same.\n\n# Parallel retrieval\nAs general guidance, Parallel Retrieval is a technique that should be used when due to query complexity, retrieval of data in a single request is significantly slower than it would otherwise be for a simple request.  Parallel retrieval does not act as a speed multiplier on optimally running queries.  By parallelizing such requests, data retrieval performance can be tuned to meet the client application needs. \n\nCDF supports parallel retrieval through the `partition` parameter, which has the format `m/n` where `n` is the amount of partitions you would like to split the entire data set into.\nIf you want to download the entire data set by splitting it into 10 partitions, do the following in parallel with `m` running from 1 to 10:\n  - Make a request to `/events` with `partition=m/10`.\n  - Paginate through the response by following the cursor as explained above. Note that the `partition` parameter needs to be passed to all subqueries.\n\nProcessing of parallel retrieval requests is subject to concurrency quota availability. The request returns the `429` response upon exceeding concurrency limits. See the Request throttling chapter below.\n\nTo prevent unexpected problems and to maximize read throughput, you should at most use 10 partitions. \nSome CDF resources will automatically enforce a maximum of 10 partitions.\nFor more specific and detailed information, please read the ```partition``` attribute documentation for the CDF resource you're using.  \n\n# Requests throttling\nCognite Data Fusion (CDF) returns the HTTP `429` (too many requests) response status code when project capacity exceeds the limit.\n\nThe throttling can happen:\n  - If a user or a project sends too many (more than allocated) concurrent requests.\n  - If a user or a project sends a too high (more than allocated) rate of requests in a given amount of time.\n\nCognite recommends using a retry strategy based on truncated exponential backoff to handle sessions with HTTP response codes 429.\n\nCognite recommends using a reasonable number (up to 10) of  `Parallel retrieval` partitions.\n\nFollowing these strategies lets you slow down the request frequency to maximize productivity without having to re-submit/retry failing requests.\n\nSee more [here](https://docs.cognite.com/dev/concepts/resource_throttling).\n\n# API versions\n## Version headers\nThis API uses calendar versioning, and version names follow the `YYYYMMDD` format.\nYou can find the versions currently available by using the version selector at the top of this page.\n\nTo use a specific API version, you can pass the `cdf-version: $version` header along with your requests to the API.\n\n## Beta versions\nThe beta versions provide a preview of what the stable version will look like in the future.\nBeta versions contain functionality that is reasonably mature, and highly likely to become a part of the stable API.\n\nBeta versions are indicated by a `-beta` suffix after the version name. For example, the beta version header for the\n2023-01-01 version is then `cdf-version: 20230101-beta`.\n\n## Alpha versions\nAlpha versions contain functionality that is new and experimental, and not guaranteed to ever become a part of the stable API.\nThis functionality presents no guarantee of service, so its use is subject to caution.\n\nAlpha versions are indicated by an `-alpha` suffix after the version name. For example, the alpha version header for\nthe 2023-01-01 version is then `cdf-version: 20230101-alpha`."
  version: v1
  contact:
    name: Cognite Support
    url: https://support.cognite.com
    email: support@cognite.com
servers:
- url: https://{cluster}.cognitedata.com/api/v1/projects/{project}
  description: The URL for the CDF cluster to connect to
  variables:
    cluster:
      enum:
      - api
      - az-tyo-gp-001
      - az-eastus-1
      - az-power-no-northeurope
      - westeurope-1
      - asia-northeast1-1
      - gc-dsm-gp-001
      default: api
      description: The CDF cluster to connect to
    project:
      default: publicdata
      description: The CDF project name.
security:
- oidc-token:
  - https://{cluster}.cognitedata.com/.default
- oauth2-client-credentials:
  - https://{cluster}.cognitedata.com/.default
- oauth2-open-industrial-data:
  - https://api.cognitedata.com/.default
- oauth2-auth-code:
  - https://{cluster}.cognitedata.com/.default
tags:
- name: Entity matching
  description: The entity matching contextualization endpoints lets you match CDF resources. For example, you can match time series to assets. The model uses similarity between string-fields from the source and the target to find potential matches, for instance the source name and the target name. The exact algorithm may change over time.
paths:
  /context/entitymatching:
    get:
      tags:
      - Entity matching
      summary: List entity matching models
      description: '


        > **Required capabilities:** `entitymatchingAcl:READ`


        List all available entity matching models, with pagination.'
      operationId: entityMatchingModels
      parameters:
      - $ref: '#/components/parameters/Cursor'
      - $ref: '#/components/parameters/StrictLimit1000'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EntityMatcherResponseSchema'
                  nextCursor:
                    $ref: '#/components/schemas/NextCursorV3'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:READ
      x-code-samples:
      - lang: Python
        label: Python SDK
        source: 'client.entity_matching.list(limit=1, name="test")

          '
    post:
      tags:
      - Entity matching
      summary: Create entity matcher model
      description: '


        > **Required capabilities:** `entitymatchingAcl:WRITE`


        Train a model that predicts matches between entities (for example, time series names to asset names). This is also known as fuzzy joining. If there are no trueMatches (labeled data), you train a static (unsupervised) model, otherwise a machine learned (supervised) model is trained.'
      operationId: entityMatchingCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - sources
              - targets
              properties:
                sources:
                  $ref: '#/components/schemas/Sources'
                targets:
                  $ref: '#/components/schemas/Targets'
                trueMatches:
                  $ref: '#/components/schemas/TrueMatches'
                externalId:
                  $ref: '#/components/schemas/CogniteExternalId'
                name:
                  $ref: '#/components/schemas/ModelName'
                description:
                  $ref: '#/components/schemas/ModelDescription'
                featureType:
                  description: "Each feature type defines one combination of features that will be created and used in the entity matcher model. All features are based on matching tokens. Tokens are defined at the top of the Entity matching section.\nThe options are:\n  * Simple: Calculates the cosine-distance similarity score for each of the pairs of fields defined in `matchFields`. This is the fastest option.\n  * Insensitive: Similar to Simple, but ignores lowercase/uppercase differences.\n  * Bigram: Similar to `simple`, but adds similarity score based on matching bigrams of the tokens.\n  * FrequencyWeightedBigram: Similar to `bigram`, but give higher weights to less commonly occurring tokens.\n  * BigramExtraTokenizers: Similar to `bigram`, but able to learn that leading zeros, spaces, and uppercase/lowercase differences should be ignored in matching.\n  * BigramCombo: Calculates all of the above options, relying on the model to determine the appropriate features to use.\n  Hence, this option is only appropriate if there are  labeled data/trueMatches. This is the slowest option.\n"
                  allOf:
                  - $ref: '#/components/schemas/FeatureType'
                matchFields:
                  $ref: '#/components/schemas/MatchFields'
                classifier:
                  $ref: '#/components/schemas/Classifier'
                ignoreMissingFields:
                  $ref: '#/components/schemas/IgnoreMissingFields'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "const result = await client.entityMatching.create({\n sources: [{externalId: 'asset1', name: 'asset1'}, {externalId: 'asset2', name: 'asset2'}],\n targets: [{externalId: 'ts1', name: 'ts1'}, {externalId: 'ts2', name: 'ts2'}],\n externalId: 'model123',\n name: 'model123',\n});"
      - lang: Java
        label: Java SDK
        source: "List<Struct> source = generateSourceStructs(); \nList<Struct> target = generateTargetTrainingStructs(); \n\n// Train the matching model \nRequest entityMatchFitRequest = Request.create() \n          .withRootParameter(\"sources\",  source) \n          .withRootParameter(\"targets\", target) \n          .withRootParameter(\"matchFields\", Map.of(\"source\", \"name\", \"target\", \"externalId\")) \n          .withRootParameter(\"featureType\", \"insensitive\"); \n\nList<EntityMatchModel> models = client.contextualization() \n          .entityMatching() \n          .create(List.of(entityMatchFitRequest)); \n\nprivate List<Struct> generateSourceStructs() { \n     Struct entityA = Struct.newBuilder() \n          .putFields(\"id\", Values.of(1D)) \n          .putFields(\"name\", Values.of(\"23-DB-9101\")) \n          .putFields(\"fooField\", Values.of(\"bar\")) \n          .build(); \n     Struct entityB = Struct.newBuilder() \n          .putFields(\"id\", Values.of(2D)) \n          .putFields(\"name\", Values.of(\"23-PC-9101\")) \n          .putFields(\"barField\", Values.of(\"foo\")) \n          .build(); \n     return List.of(entityA, entityB); \n} \n\nprivate List<Struct> generateTargetTrainingStructs() { \n    Struct targetA = Struct.newBuilder() \n          .putFields(\"id\", Values.of(1D)) \n          .putFields(\"externalId\", Values.of(\"IA-23_DB_9101\")) \n          .build(); \n     Struct targetB = Struct.newBuilder() \n          .putFields(\"id\", Values.of(2D)) \n          .putFields(\"externalId\", Values.of(\"VAL_23_PC_9101\")) \n          .build(); \n     return List.of(targetA, targetB); \n} \n\n"
  /context/entitymatching/{id}:
    get:
      tags:
      - Entity matching
      summary: Retrieve an entity matching model by the ID of the model
      description: '


        > **Required capabilities:** `entitymatchingAcl:READ`


        Shows the status of the model. If the status is completed, shows the parameters used to train the model.'
      operationId: entityMatchingStatus
      parameters:
      - $ref: '#/components/parameters/CogniteInternalId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                - classifier
                - featureType
                allOf:
                - $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:READ
  /context/entitymatching/byids:
    post:
      tags:
      - Entity matching
      summary: Retrieve entity matching models
      description: '


        > **Required capabilities:** `entitymatchingAcl:READ`


        Retrieve entity matching models by IDs or external IDs.'
      operationId: entityMatchingRetrieve
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - items
              properties:
                items:
                  $ref: '#/components/schemas/OneOfId'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:READ
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'const [result] = await client.entityMatching.retrieve([{ externalId: ''model123'' }]);'
      - lang: Python
        label: Python SDK
        source: 'retrieved_model = client.entity_matching.retrieve(id=1)

          retrieved_models = client.entity_matching.retrieve_multiple([1,2,3])

          '
  /context/entitymatching/list:
    post:
      tags:
      - Entity matching
      summary: Filter models
      description: '


        > **Required capabilities:** `entitymatchingAcl:READ`


        Use filtering options to find entity matcher models.'
      operationId: entityMatchingFilter
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - filter
              properties:
                limit:
                  description: <- Limits the number of results to return.
                  type: integer
                  format: int32
                  minimum: 1
                  maximum: 1000
                  default: 100
                filter:
                  type: object
                  allOf:
                  - description: Filter on models with strict matching.
                  - $ref: '#/components/schemas/EntityMatchingFilterSchema'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:READ
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'const { items } = await client.entityMatching.list({ filter: { name: ''model123'' }});'
  /context/entitymatching/update:
    post:
      tags:
      - Entity matching
      summary: Update entity matching models
      description: '


        > **Required capabilities:** `entitymatchingAcl:WRITE`


        Update entity matching models by IDs or external IDs.'
      operationId: entityMatchingUpdate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - items
              properties:
                items:
                  type: array
                  minItems: 1
                  maxItems: 1000
                  items:
                    $ref: '#/components/schemas/ModelChange'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - items
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "const [updated] = await client.entityMatching.update([{\n externalId: 'model123',\n update: { description: { set: 'Ã¸' }}\n}]);"
      - lang: Python
        label: Python SDK
        source: 'from cognite.client.data_classes.contextualization import EntityMatchingModelUpdate

          client.entity_matching.update(EntityMatchingModelUpdate(id=1).name.set("New name"))

          '
  /context/entitymatching/delete:
    post:
      tags:
      - Entity matching
      summary: Delete entity matcher model
      description: '


        > **Required capabilities:** `entitymatchingAcl:WRITE`


        Deletes an entity matching model. Currently, this is a soft delete, and only removes the entry from listing.'
      operationId: entityMatchingDelete
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - items
              properties:
                items:
                  $ref: '#/components/schemas/OneOfId'
      responses:
        '200':
          description: Models deleted.
          content:
            application/json:
              schema:
                type: object
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: 'await client.entityMatching.delete([{ externalId: ''model123'' }]);'
      - lang: Python
        label: Python SDK
        source: 'client.entity_matching.delete(id=1)

          '
  /context/entitymatching/predict:
    post:
      tags:
      - Entity matching
      summary: Predict matches
      description: '


        > **Required capabilities:** `entitymatchingAcl:WRITE`


        Predicts entity matches using a trained model. Note: ''assetsAcl:READ'' capability is required unless both `sources` and `targets` are specified in the request. Also note that the header of a successful response contains a `X-Job-Token` which allows to fetch the result of the job at `/context/entitymatching/jobs/{jobId}` without requiring ''assetsAcl:READ''.'
      operationId: entityMatchingPredict
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityMatchingPredictSchema'
      responses:
        '200':
          description: Success
          headers:
            X-Job-Token:
              schema:
                $ref: '#/components/schemas/JobToken'
          content:
            application/json:
              schema:
                type: object
                required:
                - jobId
                allOf:
                - properties:
                    jobId:
                      $ref: '#/components/schemas/JobId'
                - $ref: '#/components/schemas/StatusSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "const response = await client.entityMatching.predict({\n externalId: 'model123',\n sources: [{externalId: 'asset1', name: 'asset1'}, {externalId: 'asset2', name: 'asset2'}],\n targets: [{externalId: 'ts1', name: 'ts1'}, {externalId: 'ts2', name: 'ts2'}],\n});"
      - lang: Python
        label: Python SDK
        source: "sources = {'id': 101, 'name': 'ChildAsset1', 'description': 'Child of ParentAsset1'}\ntargets = {'id': 1, 'name': 'ParentAsset1', 'description': 'Parent to ChildAsset1'}\ntrue_matches = [(1, 101)]\nmodel = client.entity_matching.predict(\n    sources = sources,\n    targets = targets,\n    num_matches = 1,\n    score_threshold = 0.6,\n    id=1\n)\n"
      - lang: Java
        label: Java SDK
        source: "List<EntityMatchModel> models = // list of EntityMatchModel; \nlong modelId = models.get(0).getId(); \nList<Struct> source = generateSourceStructs(); \nList<Struct> target = generateTargetStructs(); \nList<EntityMatchResult> matchResults = client.contextualization() \n          .entityMatching() \n          .predict(modelId, source, target); \n\nprivate List<Struct> generateSourceStructs() { \n     Struct entityA = Struct.newBuilder() \n          .putFields(\"id\", Values.of(1D)) \n          .putFields(\"name\", Values.of(\"23-DB-9101\")) \n          .putFields(\"fooField\", Values.of(\"bar\")) \n          .build(); \n     Struct entityB = Struct.newBuilder() \n          .putFields(\"id\", Values.of(2D)) \n          .putFields(\"name\", Values.of(\"23-PC-9101\")) \n          .putFields(\"barField\", Values.of(\"foo\")) \n          .build(); \n     return List.of(entityA, entityB); \n} \n\nprivate List<Struct> generateTargetStructs() { \n     Struct targetA = Struct.newBuilder() \n          .putFields(\"id\", Values.of(1D)) \n          .putFields(\"externalId\", Values.of(\"IA-23_DB_9101\")) \n          .putFields(\"uuid\", Values.of(UUID.randomUUID().toString())) \n          .build(); \n     Struct targetB = Struct.newBuilder() \n          .putFields(\"id\", Values.of(2D)) \n          .putFields(\"externalId\", Values.of(\"VAL_23_PC_9101\")) \n          .putFields(\"uuid\", Values.of(UUID.randomUUID().toString())) \n          .build(); \n     return List.of(targetA, targetB); \n} \n\n"
  /context/entitymatching/jobs/{jobId}:
    get:
      tags:
      - Entity matching
      summary: Retrieve entity matcher predict results
      description: '


        > **Required capabilities:** `assetsAcl:READ` `entitymatchingAcl:WRITE`


        Get the results from a predict job. Note: ''assetsAcl:READ'' capability is required, unless you specify a valid `X-Job-Token` in the request header. The `X-Job-Token` is provided in the response header of the initial call to `/context/entitymatching/predict`'
      operationId: entityMatchingPredictResults
      parameters:
      - $ref: '#/components/parameters/jobId'
      - in: header
        name: X-Job-Token
        schema:
          $ref: '#/components/schemas/JobToken'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                - jobId
                - items
                allOf:
                - $ref: '#/components/schemas/StatusSchema'
                - properties:
                    jobId:
                      $ref: '#/components/schemas/JobId'
                    status:
                      $ref: '#/components/schemas/JobStatus'
                    items:
                      type: array
                      description: List of matched entities with confidence score.
                      items:
                        type: object
                        required:
                        - source
                        - matches
                        properties:
                          source:
                            type: object
                            example:
                              field: value
                              ignoredfield:
                                key: value
                            description: The source item given to predict.
                          matches:
                            type: array
                            required:
                            - score
                            - target
                            description: Matched items, sorted from highest score to lowest. May be empty.
                            items:
                              type: object
                              properties:
                                score:
                                  type: number
                                  example: 0.98
                                  description: The model's confidence in the match.
                                target:
                                  type: object
                                  example:
                                    field: value
                                    ignoredfield:
                                      key: value
                                  description: The target item given to predict.
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - assetsAcl:READ
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: const { status, items } = await client.entityMatching.predictResult(12345678);
  /context/entitymatching/refit:
    post:
      tags:
      - Entity matching
      summary: Re-fit entity matcher model
      description: '


        > **Required capabilities:** `entitymatchingAcl:READ` `entitymatchingAcl:WRITE`


        Creates a new model by re-training an existing model on existing data but with additional true matches. The old model is not changed. The new model gets a new id and new external id if `newExternalId` is set, or no external id if `newExternalId` is not set. Use for efficient re-training of the model after a user creates additional confirmed matches.'
      operationId: entityMatchingReFit
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EntityMatchingRefitSchema'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                required:
                - classifier
                - featureType
                - originalId
                allOf:
                - $ref: '#/components/schemas/EntityMatcherResponseSchema'
        '400':
          $ref: '#/components/responses/ErrorResponse'
      x-capability:
      - entitymatchingAcl:READ
      - entitymatchingAcl:WRITE
      x-code-samples:
      - lang: JavaScript
        label: JavaScript SDK
        source: "await client.entityMatching.refit({\n newExternalId: 'newModel123',\n sources: [{externalId: 'asset1', name: 'asset1'}, {externalId: 'asset2', name: 'asset2'}],\n targets: [{externalId: 'ts1', name: 'ts1'}, {externalId: 'ts2', name: 'ts2'}],\n externalId: 'model123',\n trueMatches: [{sourceExternalId: 'asset1', targetExternalId: 'ts1'}]\n});"
      - lang: Python
        label: Python SDK
        source: 'sources = [{''id'': 101, ''name'': ''ChildAsset1'', ''description'': ''Child of ParentAsset1''}]

          targets = [{''id'': 1, ''name'': ''ParentAsset1'', ''description'': ''Parent to ChildAsset1''}]

          true_matches = [(1, 101)]

          model = client.entity_matching.refit(true_matches = true_matches, description="AssetMatchingJob1", id=1)

          '
components:
  schemas:
    EntityMatchingRefitFeatureSchema:
      type: object
      required:
      - trueMatches
      properties:
        newExternalId:
          description: ExternalId for the new refitted model provided by client. Must be unique within the project.
          allOf:
          - $ref: '#/components/schemas/CogniteExternalId'
        trueMatches:
          description: List of additional confirmed matches used to train the model. The new model uses a combination of this and trueMatches from the orginal model. If there are identical match-from ids, the pair from the original model is dropped.
          allOf:
          - $ref: '#/components/schemas/TrueMatches'
        sources:
          description: List of source entities, for example, time series. If omitted, will use data from fit.
          allOf:
          - $ref: '#/components/schemas/Sources'
        targets:
          description: List of target entities, for example, assets. If omitted, will use data from fit.
          allOf:
          - $ref: '#/components/schemas/Targets'
    ModelDescription:
      type: string
      description: User defined description.
      example: Simple model 1
      maxLength: 500
    SourceId:
      description: The id for the from-object of the match.
      allOf:
      - $ref: '#/components/schemas/CogniteInternalId'
    MatchFields:
      type: array
      example:
      - source: name
        target: name
      - source: name
        target: someField
      default:
      - source: name
        target: name
      description: List of pairs of fields from the target and source items, used to calculate features. All source and target items should have all the `source` and `target` fields specified here.
      items:
        type: object
        required:
        - source
        - target
        properties:
          source:
            type: string
          target:
            type: string
    EntityMatchingFilterSchema:
      type: object
      properties:
        featureType:
          $ref: '#/components/schemas/FeatureType'
        classifier:
          $ref: '#/components/schemas/Classifier'
        originalId:
          type: integer
          description: The ID of original model, only relevant when the model is a retrained model.
          example: 111
        name:
          $ref: '#/components/schemas/ModelName'
        description:
          $ref: '#/components/schemas/ModelDescription'
    EntityMatchingRefitSchema:
      type: object
      oneOf:
      - allOf:
        - type: object
          required:
          - id
          properties:
            id:
              description: The ID of the original model.
              allOf:
              - $ref: '#/components/schemas/CogniteInternalId'
        - $ref: '#/components/schemas/EntityMatchingRefitFeatureSchema'
      - allOf:
        - type: object
          required:
          - externalId
          properties:
            externalId:
              description: The externalId of the original model.
              allOf:
              - $ref: '#/components/schemas/CogniteExternalId'
        - $ref: '#/components/schemas/EntityMatchingRefitFeatureSchema'
    CogniteExternalId:
      description: The external ID provided by the client. Must be unique for the resource type.
      type: string
      maxLength: 255
      example: my.known.id
    ModelChangeById:
      allOf:
      - $ref: '#/components/schemas/ModelPatch'
      - type: object
        required:
        - id
        properties:
          id:
            $ref: '#/components/schemas/CogniteInternalId'
    ModelName:
      type: string
      description: User defined name.
      example: simple_model_1
      maxLength: 256
    SinglePatchRequiredModelDescription:
      title: Description
      type: object
      properties:
        set:
          $ref: '#/components/schemas/ModelDescription'
      description: Set a new value for description.
      required:
      - set
    StatusSchema:
      type: object
      required:
      - status
      - createdTime
      - startTime
      - statusTime
      properties:
        status:
          $ref: '#/components/schemas/JobStatus'
        createdTime:
          $ref: '#/components/schemas/EpochTimestamp'
        startTime:
          $ref: '#/components/schemas/EpochTimestamp'
        statusTime:
          $ref: '#/components/schemas/EpochTimestamp'
        errorMessage:
          type: string
          description: If the job failed, some more information about the error cause.
          example: null
          default: null
    CogniteInternalId:
      description: A server-generated ID for the object.
      type: integer
      minimum: 1
      maximum: 9007199254740991
      format: int64
    Targets:
      type: array
      minItems: 1
      maxItems: 2000000
      items:
        type: object
        example:
          id: 6
          name: some_name
          somefield: value
          ignoredfield:
            key: value
      description: List of custom target object to match to, for example, assets. String key -> value. Only string values are considered in the matching. Both `id` and `externalId` fields are optional, only mandatory if the item is to be referenced in `trueMatches`.
    Error:
      type: object
      required:
      - code
      - message
      description: Cognite API error.
      properties:
        code:
          type: integer
          description: HTTP status code.
          format: int32
          example: 401
        message:
          type: string
          description: Error message.
          example: Could not authenticate.
        missing:
          type: array
          description: List of lookup objects that do not match any results.
          items:
            type: object
            additionalProperties: true
        duplicated:
          type: array
          description: List of objects that are not unique.
          items:
            type: object
            additionalProperties: true
    ModelChangeByExternalId:
      allOf:
      - $ref: '#/components/schemas/ModelPatch'
      - type: object
        required:
        - externalId
        properties:
          externalId:
            $ref: '#/components/schemas/CogniteExternalId'
    EntityMatcherResponseSchema:
      type: object
      required:
      - id
      - externalId
      - name
      - description
      allOf:
      - properties:
          id:
            $ref: '#/components/schemas/CogniteInternalId'
          externalId:
            $ref: '#/components/schemas/CogniteExternalId'
      - $ref: '#/components/schemas/StatusSchema'
      - $ref: '#/components/schemas/EntityMatchingFeatureSchema'
    TargetExternalId:
      description: The external id for the to-object of the match.
      allOf:
      - $ref: '#/components/schemas/CogniteExternalId'
    TargetId:
      description: The id for the target-object of the match.
      allOf:
      - $ref: '#/components/schemas/CogniteInternalId'
    EntityMatchingPredictSchema:
      type: object
      oneOf:
      - allOf:
        - type: object
          required:
          - id
          properties:
            id:
              description: The ID of the model that is used to predict matches.
              allOf:
              - $ref: '#/components/schemas/CogniteInternalId'
        - $ref: '#/components/schemas/EntityMatchingPredictFeatureSchema'
      - allOf:
        - type: object
          required:
          - externalId
          properties:
            externalId:
              description: The externalId of the model that is used to predict matches.
              allOf:
              - $ref: '#/components/schemas/CogniteExternalId'
        - $ref: '#/components/schemas/EntityMatchingPredictFeatureSchema'
    Sources:
      type: array
      minItems: 0
      maxItems: 2000000
      items:
        type: object
        example:
          id: 10
          name: a_name
          field: value
          ignoredfield:
            key: value
      description: List of custom source object to match from, for example, time series. String key -> value. Only string values are considered in the matching. Both `id` and `externalId` fields are optional, only mandatory if the item is to be referenced in `trueMatches`.
    EntityMatchingFeatureSchema:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/ModelName'
        description:
          $ref: '#/components/schemas/ModelDescription'
        featureType:
          $ref: '#/components/schemas/FeatureType'
        matchFields:
          $ref: '#/components/schemas/MatchFields'
        ignoreMissingFields:
          description: If True, missing fields in `sources` or `targets` entities set in `matchFields`, are replaced with empty strings.
          allOf:
          - $ref: '#/components/schemas/IgnoreMissingFields'
        classifier:
          description: Name of the classifier used in the model, "Unsupervised" if unsupervised model.
          allOf:
          - $ref: '#/components/schemas/Classifier'
        originalId:
          type: integer
          description: The ID of original model, only relevant when the model is a retrained model.
          example: 111
    JobId:
      description: Contextualization job ID.
      type: integer
      example: 123
      format: int64
    EpochTimestamp:
      description: The number of milliseconds since 00:00:00 Thursday, 1 January 1970, Coordinated Universal Time (UTC), minus leap seconds.
      type: integer
      minimum: 0
      format: int64
      example: 1730204346000
    JobToken:
      type: string
      description: A string token that can be attached to the header of a request fetching the job status. Authenticates the user fetching the job status as the same one who originally posted the job.
    ModelChange:
      oneOf:
      - $ref: '#/components/schemas/ModelChangeById'
      - $ref: '#/components/schemas/ModelChangeByExternalId'
    OneOfId:
      type: array
      example:
      - id: 2563587950655335
      - externalId: myUniqueName
      description: List of ids or externalIds of models.
      minItems: 1
      maxItems: 1000
      items:
        oneOf:
        - type: object
          required:
          - id
          properties:
            id:
              $ref: '#/components/schemas/CogniteInternalId'
        - type: object
          required:
          - externalId
          properties:
            externalId:
              $ref: '#/components/schemas/CogniteExternalId'
    NextCursorV3:
      description: The cursor value used to return (paginate to) the next page of results, when more data is available.
      type: string
    FeatureType:
      type: string
      example: simple
      enum:
      - simple
      - insensitive
      - bigram
      - frequencyweightedbigram
      - bigramextratokenizers
      - bigramcombo
      default: simple
      description: Each feature type defines the combination of features that will be created and used in the entity matcher model.
    ModelPatch:
      type: object
      description: Changes applied to model
      required:
      - update
      properties:
        update:
          type: object
          properties:
            name:
              $ref: '#/components/schemas/SinglePatchRequiredModelName'
            description:
              $ref: '#/components/schemas/SinglePatchRequiredModelDescription'
    TrueMatches:
      type: array
      description: 'A list of confirmed source/target matches, which will be used to train the model. If omitted, an unsupervised

        model is trained.'
      minItems: 1
      maxItems: 2000000
      items:
        $ref: '#/components/schemas/Match'
    SourceExternalId:
      description: The external id for the source-object of the match.
      allOf:
      - $ref: '#/components/schemas/CogniteExternalId'
    Match:
      type: object
      description: 'A pair of source ID and target ID, that indicates a match between two entities in the source and target spaces.

        Internal and external IDs are supported.'
      example:
        sourceId: 23
        targetExternalId: my.known.id
      oneOf:
      - properties:
          sourceId:
            $ref: '#/components/schemas/SourceId'
          targetId:
            $ref: '#/components/schemas/TargetId'
        required:
        - sourceId
        - targetId
      - properties:
          sourceId:
            $ref: '#/components/schemas/SourceId'
          targetExternalId:
            $ref: '#/components/schemas/TargetExternalId'
        required:
        - sourceId
        - targetExternalId
      - properties:
          sourceExternalId:
            $ref: '#/components/schemas/SourceExternalId'
          targetId:
            $ref: '#/components/schemas/TargetId'
        required:
        - sourceExternalId
        - targetId
      - properties:
          sourceExternalId:
            $ref: '#/components/schemas/SourceExternalId'
          targetExternalId:
            $ref: '#/components/schemas/TargetExternalId'
        required:
        - sourceExternalId
        - targetExternalId
    IgnoreMissingFields:
      type: boolean
      default: false
      example: true
      description: If True, replaces missing fields in `sources` or `targets` entities, for fields set in set in `matchFields`, with empty strings. Else, returns an error if there are missing data.
    JobStatus:
      description: The status of the job.
      type: string
      enum:
      - Queued
      - Running
      - Completed
      - Failed
    SinglePatchRequiredModelName:
      title: Name
      type: object
      properties:
        set:
          $ref: '#/components/schemas/ModelName'
      description: Set a new value for name.
      required:
      - set
    EntityMatchingPredictFeatureSchema:
      type: object
      properties:
        sources:
          description: List of source entities to predict matches for, for example, time series. If omitted, will use `sources` from create and `assetsAcl:READ` capability will be required for the request.
          allOf:
          - $ref: '#/components/schemas/Sources'
        targets:
          description: List of potential target entities to match to one or more of the source entities, for example, assets. If omitted, will use `targets` from create and `assetsAcl:READ` capability will be required for the request.
          allOf:
          - $ref: '#/components/schemas/Targets'
        numMatches:
          type: integer
          example: 3
          minimum: 0
          maximum: 100
          description: The maximum number of results to return for each source entity.
        scoreThreshold:
          type: number
          example: 0.7
          minimum: 0
          maximum: 1
          description: Only return matches with score above this threshold.
    Classifier:
      type: string
      description: The classifier used in the model. Only relevant if there are trueMatches/labeled data and a supervised model is fitted.
      example: randomforest
      default: randomforest
      enum:
      - randomforest
      - decisiontree
      - logisticregression
      - augmentedlogisticregression
      - augmentedrandomforest
  parameters:
    CogniteInternalId:
      in: path
      name: id
      required: true
      schema:
        $ref: '#/components/schemas/CogniteInternalId'
    jobId:
      in: path
      name: jobId
      required: true
      schema:
        $ref: '#/components/schemas/JobId'
    StrictLimit1000:
      name: limit
      description: Limits the number of results to be returned.
      in: query
      schema:
        type: integer
        default: 100
        minimum: 1
        maximum: 1000
    Cursor:
      name: cursor
      description: 'Cursor for paging through results. In general, if a response contains a `nextCursor`

        property, it means that there may be more results, and you should pass that value as the

        `cursor` parameter in the next request.


        Note that the cursor may or may not be encrypted, but either way, it is not intended to be

        decoded. Its internal structure is not a part of the public API, and may change without

        notice. You should treat it as an opaque string and not attempt to craft your own cursors.

        '
      in: query
      schema:
        type: string
        example: 4zj0Vy2fo0NtNMb229mI9r1V3YG5NBL752kQz1cKtwo
  responses:
    ErrorResponse:
      description: The response for a failed request.
      content:
        application/json:
          schema:
            type: object
            required:
            - error
            properties:
              error:
                $ref: '#/components/schemas/Error'
  securitySchemes:
    oidc-token:
      type: http
      scheme: bearer
      bearerFormat: OpenID Connect or OAuth2 token
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
    oauth2-client-credentials:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        clientCredentials:
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-auth-code:
      type: oauth2
      description: Access token issued by the CDF project's configured identity provider. Access token must be an OpenID Connect token, and the project must be configured to accept OpenID Connect tokens. Use a header key of 'Authorization' with a value of 'Bearer $accesstoken'. The token can be obtained through any flow supported by the identity provider.
      flows:
        authorizationCode:
          authorizationUrl: https://your-idps.authorization.url/
          tokenUrl: https://your-idps.token.url/
          scopes:
            default: https://{cluster}.cognitedata.com/.default
    oauth2-open-industrial-data:
      type: oauth2
      description: Auth flow for Open Industrial Data. Get your client secret from https://hub.cognite.com/open-industrial-data-211.
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/48d5043c-cf70-4c49-881c-c638f5796997/oauth2/v2.0/token
          scopes:
            default: https://api.cognitedata.com/.default
    org-oidc-token:
      type: openIdConnect
      openIdConnectUrl: https://auth.cognite.com/.well-known/openid-configuration
      description: 'Access token issued by the Cognite authorization server, and valid for the target organization. The token must

        be an OpenID Connect token, and it can be obtained by performing an OIDC login flow toward `auth.cognite.com`.

        This is a single URL for all CDF organizations.'
x-tagGroups:
- name: Changelog
  tags:
  - Changelog
- name: Organizations and projects
  tags:
  - Organizations
  - Projects
- name: Identity and access management
  tags:
  - Principals
  - Groups
  - Security categories
  - Sessions
  - Token
  - User profiles
  - Project Deletion Reporting
- name: Data modeling
  tags:
  - Data Modeling
  - Data models
  - Spaces
  - Views
  - Containers
  - Nodes
  - Instances
  - Statistics
  - Streams
  - Records
- name: Asset-centric data model
  tags:
  - Assets
  - Time series
  - Synthetic Time Series
  - Data point subscriptions
  - Events
  - Files
  - Sequences
  - Geospatial
  - Seismic
- name: 3D
  tags:
  - 3D Models
  - 3D Model Revisions
  - 3D Files
  - 3D Asset Mapping
  - 3D Contextualization
  - 3D Jobs
  - 3D Migration
  - 3D Scenes
- name: Contextualization
  tags:
  - Entity matching
  - Entity matching pipelines
  - Engineering diagrams
  - Vision
  - Advanced joins
- name: Cognite AI
  tags:
  - Agents
  - Skills
  - Chat Completions
  - Document AI
  - Models
- name: Documents
  tags:
  - Documents
  - Document preview
- name: Data ingestion
  tags:
  - Raw
  - Extraction Pipelines
  - Extraction Pipelines Runs
  - Extraction Pipelines Config
  - Extractors
- name: Data organization
  tags:
  - Data sets
  - Data domains
  - Data products
  - Rule sets
  - Labels
  - Relationships
  - Annotations
- name: Transformations
  tags:
  - Transformations
  - Transformation Jobs
  - Transformation Schedules
  - Transformation Notifications
  - Query
  - Schema
- name: Functions
  tags:
  - Functions
  - Function calls
  - Function schedules
- name: Hosted Extractors
  tags:
  - Sources
  - Jobs
  - Destinations
  - Mappings
- name: PostgreSQL Gateway
  tags:
  - Postgres Gateway Users
  - Postgres Gateway Tables
- name: SAP Writeback
  tags:
  - SAP Instances
  - SAP Endpoints
  - Schema Mappings
  - Writeback Requests
- name: Data workflows
  tags:
  - Workflows
  - Workflow versions
  - Workflow executions
  - Workflow triggers
  - Tasks
  - Workers
- name: Simulators
  tags:
  - Simulators
  - Simulator Integrations
  - Simulator Models
  - Simulator Routines
  - Simulation Runs
  - Simulator Logs
- name: Units
  tags:
  - Units
  - Unit Systems
- name: ''
  tags:
  - ''
